---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: nginx-ingress
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 1.1.0
  values:
    meshProvider: nginx
    #    metricsServer: http://prometheus.nginx-ingress:9090
    prometheus:
      install: true
#    slack:
#      url: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
#      user: flagger
#      channel: general